spring:
  application:
    name: cicd-demo

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:postgres}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:root123}
    hikari:
      maximum-pool-size: ${DB_POOL_SIZE:10}
      connection-timeout: 5000

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false


server:
  port: ${SERVER_PORT:8080}
  shutdown: graceful

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: ${ACTUATOR_SHOW_DETAILS:never}
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    com.example.cicddemo: DEBUG
